[project]
name = "dbos-py-benchmark-app"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Qian Li", email = "qian.li@dbos.dev"},
]
dependencies = [
    "dbos @ file:///${PROJECT_ROOT}/dbos-0.16.0a22+g38d1dea-py3-none-any.whl",
    "aiohttp>=3.11.10",
    "numpy>=2.0.2",
]
requires-python = ">3.9"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
